added env variable -1

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -65,36 +65,36 @@ commands:
             sudo add-apt-repository --yes --update ppa:ansible/ansible
             sudo apt install ansible
 
-  # revert-migrations:
-  #   parameters:
-  #     workflow_id:
-  #       type: string
-  #   steps:
-  #     - run:
-  #         name: Reverting migrations
-  #         when: on_fail
-  #         command: |
-  #           SUCCESS=$(curl "https://kvdb.io/LHFkzdfqGQiT5AocazCCLL//migration_<<parameters.workflow_id>>" -H "X-Api-Key: ${THISDB_API_KEY}")
-  #           if (($SUCCESS == 1)); then
-  #             cd backend
-  #             npm install
-  #             npm run migrations:revert
-  #           fi
   revert-migrations:
-    description: Revert the last migration if successfully run in the current workflow.
     parameters:
       workflow_id:
         type: string
     steps:
       - run:
-          name: Revert migrations
+          name: Reverting migrations
           when: on_fail
           command: |
-            cd ~/project/backend
-            if [[ -f "~/project/.circleci/outputs/db_migration_success" ]]; then
-              npm i
-              npm run migration:revert
+            SUCCESS=$(curl "https://kvdb.io/D4iWiEhExxPtYxYMVPp3pq//migration_<<parameters.workflow_id>>" -H "X-Api-Key: ${THISDB_API_KEY}")
+            if (($SUCCESS == 1)); then
+              cd backend
+              npm install
+              npm run migrations:revert
             fi
+  # revert-migrations:
+  #   description: Revert the last migration if successfully run in the current workflow.
+  #   parameters:
+  #     workflow_id:
+  #       type: string
+  #   steps:
+  #     - run:
+  #         name: Revert migrations
+  #         when: on_fail
+  #         command: |
+  #           cd ~/project/backend
+  #           if [[ -f "~/project/.circleci/outputs/db_migration_success" ]]; then
+  #             npm i
+  #             npm run migration:revert
+  #           fi
 jobs:
   build-frontend:
     docker:
@@ -286,12 +286,23 @@ jobs:
   #     - restore_cache:
   #         keys:
   #           - build-backend
-  #     - write-env-variables
+  #     # - write-env-variables
   #     - run:
   #         name: Run migrations
   #         no_output_timeout: 20m
   #         command: |
   #           pwd
+  #           echo "BUILDING THE BACKEND ENVIRONMENT FILE FOR POSTGRES MIGRATIONS"
+  #           echo ENVIROMENT=production > .env
+  #           echo TYPEORM_CONNECTION=postgres >> .env
+  #           echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> .env
+  #           echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> .env
+  #           echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> .env
+  #           echo TYPEORM_HOST=database-1.crdvki0lcqni.us-east-1.rds.amazonaws.com >> .env
+  #           echo TYPEORM_PORT=5432 >> .env
+  #           echo TYPEORM_USERNAME=postgres >> .env
+  #           echo TYPEORM_PASSWORD=password >> .env
+  #           echo TYPEORM_DATABASE=postgres >> .env
   #           cd backend
   #           cat .env
   #           npm install
@@ -312,16 +323,17 @@ jobs:
 
   #           # if grep -q "has been executed successfully"  ./backend/migrations_dump.txt
   #           # then
-  #           #   curl https://kvdb.io/LHFkzdfqGQiT5AocazCCLL//migration_${CIRCLE_WORKFLOW_ID:0:7} \
+  #           #   curl https://kvdb.io/D4iWiEhExxPtYxYMVPp3pq//migration_${CIRCLE_WORKFLOW_ID:0:7} \
   #           #     -H "X-Api-Key: ${THISDB_API_KEY}" \
   #           #     -d "1"
   #           # else
-  #           #   curl https://kvdb.io/LHFkzdfqGQiT5AocazCCLL//migration_${CIRCLE_WORKFLOW_ID:0:7} \
+  #           #   curl https://kvdb.io/D4iWiEhExxPtYxYMVPp3pq//migration_${CIRCLE_WORKFLOW_ID:0:7} \
   #           #     -H "X-Api-Key: ${THISDB_API_KEY}" \
   #           #     -d "0"
   #           # fi
   #     - destroy-environment:
   #         workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"
+
   run-migrations:
     docker:
       - image: python:3.9.1-alpine3.12
@@ -342,11 +354,11 @@ jobs:
             echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> .env
             echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> .env
             echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> .env
-            echo TYPEORM_HOST=database-2.crcmxnn6pmse.us-west-1.rds.amazonaws.com >> .env
+            echo TYPEORM_HOST=database-1.crdvki0lcqni.us-east-1.rds.amazonaws.com >> .env
             echo TYPEORM_PORT=5432 >> .env
             echo TYPEORM_USERNAME=postgres >> .env
             echo TYPEORM_PASSWORD=password >> .env
-            echo TYPEORM_DATABASE=prasad >> .env
+            echo TYPEORM_DATABASE=postgres >> .env
             ls -latr
             cat .env
             echo "INSTALLING NPM MODULE DEPENDENCIES"
@@ -378,17 +390,27 @@ jobs:
                 echo "$MIGRATION_LOG exists."
             fi
             if grep -q "has been executed successfully" $MIGRATION_LOG; then
-              echo "SUCCESSFULLY EXECUTED THE DATABASE MIGRATIONS"
-              echo "Writing out to memstash : https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}"
-              curl -H "Content-Type: text/plain" -H "token: sjgt270867" --request PUT \
-                --data "Migration successful" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+            echo "SUCCESSFULLY EXECUTED THE DATABASE MIGRATIONS"
+            echo "Writing out to memstash : https://kvdb.io//D4iWiEhExxPtYxYMVPp3pq//migration_${CIRCLE_WORKFLOW_ID:0:7}"
+            curl https://kvdb.io/D4iWiEhExxPtYxYMVPp3pq/migration_${CIRCLE_WORKFLOW_ID:0:7} \
+              -d "1"
             else
               echo "FAILED TO RUN THE DATABASE MIGRATIONS"
-              echo "Writing out to memstash : https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}"
-              curl -H "Content-Type: text/plain" -H "token: sjgt270867" --request PUT \
-                --data "Migration failed" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+              curl https://kvdb.io/D4iWiEhExxPtYxYMVPp3pq/migration_${CIRCLE_WORKFLOW_ID:0:7} \
+                -d "0"
               exit 1
             fi
+
+
+            #   curl -H "Content-Type: text/plain" -H "token: sjgt270867" --request PUT \
+            #     --data "Migration successful" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+            # else
+            #   echo "FAILED TO RUN THE DATABASE MIGRATIONS"
+            #   echo "Writing out to memstash : https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}"
+            #   curl -H "Content-Type: text/plain" -H "token: sjgt270867" --request PUT \
+            #     --data "Migration failed" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+            #   exit 1
+            # fi
   # deploy-frontend:
   #   docker:
   #     # Docker image here that supports AWS CLI
@@ -618,8 +640,7 @@ jobs:
             OldWorkflowID=$(aws cloudformation \
             list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
             --no-paginate --output text)
-            curl https://kvdb.io/LHFkzdfqGQiT5AocazCCLL//migration_${CIRCLE_WORKFLOW_ID:0:7} \
-            -H "X-Api-Key: ${THISDB_API_KEY}" \
+            curl https://kvdb.io/D4iWiEhExxPtYxYMVPp3pq//migration_${CIRCLE_WORKFLOW_ID:0:7} \
             -d "$OldWorkflowID"
             export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
               --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
